version: "3.3"
services:
  web-base:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-base
    ports:
      - "8081:80"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3308:3306"
